### ISSUE TITLE
Setting style in form-tag of overriden fosuser register_content does not set the class of the form

### ISSUE THREAD

**Issue by ghost** [braincrafted/bootstrap-bundle#199]
my composer.json:

``` json
{
    "name" : "symfony/framework-standard-edition",
    ....
    "require" : {
        "symfony/symfony" : "~2.4",
        ...
        "friendsofsymfony/user-bundle" : "dev-master",
        ...
        "braincrafted/bootstrap-bundle" : "dev-develop"
     },
    "minimum-stability" : "stable",
     ....
     "extra" : {
        "branch-alias" : {
            "dev-master" : "2.4-dev"
        },
      ...
}
```

I updated via composer just a few minutes ago.
My Userbundle extends the FOSUserBundle. I override the register_content.html.twig by putting it under Resources/views/registration.
Putting content into it is shown in the browser so overriding works. If i try to set the style to horizontal the class is not set:

``` twig
{{ form_start(form, { 'style': 'horizontal' }) }}
<h1>Bootstrap style: {{ bootstrap_get_style()  }}</h1>
{{ form_end(form) }}
```

I override the layout.html.twig as well to extend my base_layout. bootstrap_get_style() returns nothing. And the form-tag class is not set in HTML.
Howerver the form-fields are rendered as expected i think:

``` html
<form name="fos_user_registration_form" method="post" action="">
<h1>Bootstrap style: </h1>
<div class="form-group">
  <label for="fos_user_registration_form_email" class="required">Ihre E-Mail-Adresse</label>
  <input type="email" id="fos_user_registration_form_email" name="fos_user_registration_form[email]" required="required" placeholder="Ihre E-Mail-Adresse" />
  </div>
<div class="form-group">
....
```

I deactivated assetic in the config.yml because i install js via bower:

``` yml
assetic:
    ...
    assets:
    ...
        bc_bootstrap_js: "%kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js"
....
#Braincrafted Bootstrap Configuration           
braincrafted_bootstrap:
    auto_configure:
        assetic: false
...
```

Is this a matter of configuration or do i have to tell FOSUserBundle something i don't know? I need your help! Thanks for your effort!
