### ISSUE TITLE
Problem generation bootstrap.less with custom variables.less

### ISSUE THREAD

**Issue by mumia** [braincrafted/bootstrap-bundle#300]
This is my config:

```
braincrafted_bootstrap:
    output_dir: ~
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../components/jquery/dist/jquery.js
    less_filter: less
    fonts_dir: %kernel.root_dir%/../web/fonts
    icon_prefix: glyphicon
    fontawesome_dir: %kernel.root_dir%/../components/fortawesome/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: %kernel.root_dir%/Resources/less/variables.less
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
```

When I run:

```
$ app/console braincrafted:bootstrap:generate
```

I get:

```
Found custom variables file. Generating...

[Symfony\Component\DependencyInjection\Exception\InactiveScopeException]
You cannot create a service ("templating.helper.assets") of an inactive scope ("request").
```

I assume this has to do with the compilation of the template for the custom bootstrap.less, but have no clue how to solve it.

Any ideas?
