### ISSUE TITLE
Can't generate bootstrap.scss file, says bundle must be a less filter

### ISSUE THREAD

**Issue by bkosborne** [braincrafted/bootstrap-bundle#340]
I've used this bundle with LESS in the past but wanted to try SASS for a new project. I'm at the point where I want to use my own variables.scss file. I've copied the one from the bootstrap I have (`"twbs/bootstrap-sass": "3.2.*"`) into my app's Resources folder.

I've updated the config like so:

```
braincrafted_bootstrap:
    less_filter: sass
    customize:
        variables_file: %kernel.root_dir%/Resources/bootstrap/variables.scss
```

When I run `app/console braincrafted:bootstrap:generate` to generate the bootstrap.scss file, I get an error:

```
Bundle must be configured with "less" or "lessphp" to generated bootstrap.less
```

Seems like the generator command is not yet compatible with a SASS filter?

**Comment by florianeckerstorfer** [comment]
Sorry, I missed that issue. If you still support with this please reopen.

**Comment by bkosborne** [comment]
I decided to stick with LESS because of this issue, so I never found a workaround or anything. Maybe on the next project I will try again.

**Comment by adpauly** [comment]
Hi,

I have exactly the same issue, anyone found a solution?

**Comment by dkisselev** [comment]
It looks like #412 renames less_filter to css_preprocessor and the configuration does allow SCSS, but the GenerateCommand has not been updated to accept anything other than less:

https://github.com/lashus/bootstrap-bundle/blob/master/Command/GenerateCommand.php#L70-L77

**Comment by tackerm** [comment]
This works for me  (`dev-develop` branch)

```
braincrafted_bootstrap:
    css_preprocessor: scssphp
    jquery_path: %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
    icon_prefix: fa
    customize:
        variables_file: %kernel.root_dir%/Resources/sass/variables.scss
```
