### ISSUE TITLE
No less filter in prod environment

### ISSUE THREAD

**Issue by stakido** [braincrafted/bootstrap-bundle#343]
When I run command `php app/console assetic:dump --env=prod`, I have error:
  `[InvalidArgumentException]  
  There is no "less" filter. `

My config.yml is:
```yml
assetic:
    filters:        
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
braincrafted_bootstrap:
    less_filter: less
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
```

When I run `php app/console assetic:dump`, all is OK.

What I do wrong?
