### ISSUE TITLE
Using variables.less breaks the icon path

### ISSUE THREAD

**Issue by jstoeffler** [braincrafted/bootstrap-bundle#372]
Hi,

I've been struggling with this issue for a while : when I configure the bundle to use a custom variable.less, it changes the glyphicon font file path from

    src: url('../fonts/glyphicons-halflings-regular.eot');

to 

    src: url('../../../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot');

I've tried everything, it breaks all the time, even if the variables.less file is empty, unless I remove this line :

        variables_file: %kernel.root_dir%/Resources/less/variables.less

Everything else work fine, the variable.less changes the bootstrap style. No other specific issue.
If somebody could help on this... Here's my configuration :

    assetic:
        debug:          "%kernel.debug%"
        use_controller: false
        bundles:        []
        #java: /usr/bin/java
        filters:
            lessphp:
                 file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
                 apply_to: "\.less$"
            cssrewrite: ~
        assets:
            typeahead_js:
                input: "%kernel.root_dir%/../vendor/twitter/typeahead.js/dist/typeahead.bundle.js"
                output: js/typeahead.min.js

    braincrafted_bootstrap:
        less_filter: lessphp
        customize:
            variables_file: %kernel.root_dir%/Resources/less/variables.less

I'm using :

      "symfony/symfony": "2.3.*",
      "braincrafted/bootstrap-bundle": "~2.1",
      "oyejorge/less.php": "1.7.*",

**Comment by vrnagy** [comment]
Try to add this to braincrafted_bootstrap:
```fonts_dir: %kernel.root_dir%/../web/fonts```

Like this:
```
braincrafted_bootstrap:
    less_filter: lessphp
    customize:
        variables_file: %kernel.root_dir%/Resources/less/variables.less
        fonts_dir: %kernel.root_dir%/../web/fonts
```
