### ISSUE TITLE
DateTime render

### ISSUE THREAD

**Issue by fcpauldiaz** [braincrafted/bootstrap-bundle#425]
I'm rendering a datetime field but it renders like this:

![captura de pantalla 2016-02-07 16 56 29](https://cloud.githubusercontent.com/assets/4523284/12875992/fe77f8ca-cdbb-11e5-800d-f9fc492b9a17.png)

They should be in the same row, how can I do that? And how can I change the format ? 

This is my only config and I'm using the 2.2.0 version:

``` yml
braincrafted_bootstrap:
    css_preprocessor: lessphp
    jquery_path: %kernel.root_dir%/../web/js/jquery-2.1.1.min.js

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

```
