### ISSUE TITLE
Fatal error when using custom variables.less

### ISSUE THREAD

**Issue by kingkero** [braincrafted/bootstrap-bundle#427]
I wanted to add a custom variables.less. However, `braincrafted:bootstrap:generate` returns this error

> [Symfony\Component\Debug\Exception\FatalThrowableError]  
>  Fatal error: Call to undefined method appDevDebugProjectContainer::enterScope() 

I use braincrafted/bootstrap-bundle v2.2.0, twbs/bootstrap v3.3.6, symfony/assetic-bundle v2.8.0 config as follows

```
assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\\.less$"
        cssrewrite: ~

braincrafted_bootstrap:
    css_preprocessor: less
    jquery_path: "%kernel.root_dir%/../vendor/components/jquery/jquery.min.js"
    customize:
        variables_file: "%kernel.root_dir%/Resources/less/variables.less"
    auto_configure:
        assetic: true
        twig: true
```

(I know getting started suggests to use `apply_to: "\.less$"`, this will break `assetic:dump` whereas `apply_to: "\\.less$"` does work fine for me). I tried with multiple variables.less files, also copied the bootstrap.less from twbs, none changed a thing.

Complete error message/trace

```
martin:myproject $ php bin/console braincrafted:bootstrap:generate -vvv
Found custom variables file. Generating...

  [Symfony\Component\Debug\Exception\FatalThrowableError]                          
  Fatal error: Call to undefined method appDevDebugProjectContainer::enterScope()  

Exception trace:
 () at /xxx/vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Command/GenerateCommand.php:108
 Braincrafted\Bundle\BootstrapBundle\Command\GenerateCommand->executeGenerateBootstrap() at /xxx/vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Command/GenerateCommand.php:80
 Braincrafted\Bundle\BootstrapBundle\Command\GenerateCommand->execute() at /xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:807
 Symfony\Component\Console\Application->doRunCommand() at /xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /xxx/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /xxx/bin/console:29

braincrafted:bootstrap:generate [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by marlenesco** [comment]
I have the same thing, anyone can help?

`php bin/console braincrafted:bootstrap:generate`

```

assetic:
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: '\.less$'
        cssrewrite: ~
    assets:
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../web/less/bootstrap.less"
            filters:
                - less
                - cssrewrite
            output:  "css/style.css"

braincrafted_bootstrap:
    auto_configure:
        assetic: false
    assets_dir: "%kernel.root_dir%/../web/vendor/bootstrap"
    css_preprocessor: less
    icon_prefix: fa
    fontawesome_dir: "%kernel.root_dir%/../web/vendor/font-awesome"
    fonts_dir: "%kernel.root_dir%/../web/vendor/bootstrap/fonts"
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: "%kernel.root_dir%/../web/less/variable.less"
        bootstrap_output: "%kernel.root_dir%/../web/less/bootstrap.less"
```

Thanks
