### ISSUE TITLE
".../vendor/twbs/bootstrap/less/bootstrap.less" does not exist" error when dumping for prod

### ISSUE THREAD

**Issue by jcfrane** [braincrafted/bootstrap-bundle#460]
Hi,

I followed the Getting started section of the documentation where i install less file using npm.

This is my config.yml:

```
assetic:
filters:
    less:
        node: /usr/local/bin/node
        node_paths: [/usr/local/lib/node_modules]
        apply_to: "\\.less$"
    cssrewrite: ~
braincrafted_bootstrap:
css_preprocessor: less
```

When i dump my assets in prod it tells me that twbs/bootstrap is missing... Why is assetic looking on that file? Thanks.
