### ISSUE TITLE
Ability for a custom Variables.less

### ISSUE THREAD

**Issue by bassrock** [braincrafted/bootstrap-bundle#47]
Hi All,

I am trying to add a custom variables.less file by doing the following:

```
assets:
    bootstrap_css:
        inputs:
            - %kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less
            - %kernel.root_dir%/../vendor/twitter/bootstrap/less/responsive.less
            - %kernel.root_dir%/../src/DABSquared/CurveuBundle/Resources/doc/variables.less
```

My variables.less file does not seem to be overriding the base bootstrap one. I would prefer not to have to edit the base bootstrap files. Is the correct way of going about this or is their another way I seem to be missing?

Any help would be appreciated Thanks,

Daniel
