### ISSUE TITLE
boostrap-bundle always overrides (prepends) twig form config

### ISSUE THREAD

**Issue by christian-ehmig** [braincrafted/bootstrap-bundle#78]
The docs say:
BootstrapBundle automatically styles every form in your application with Twitter Bootstrap. If you want to use a different form theme than the one provided by BootstrapBundle, you can change your Twig configuration

``` yml
twig:
    form:
        resources:
            - "AcmeBundle:Form:form_div_layout.html.twig"
```

However, here https://github.com/braincrafted/bootstrap-bundle/blob/develop/DependencyInjection/BcBootstrapExtension.php#L129

the form config is always prepended to any configuration in app/config.yml. That actually means you cannot override the default boostrap-bundle form via app/config.yml as stated in the docs.

Any suggestion how to override "BcBootstrapBundle:Form:form_div_layout.html.twig" is welcome.
